export const dummyData = [
  {
    draft_status: 'published',
    total_time_minutes: null,
    video_url: 'https://vid.tasty.co/output/121934/hls24_1546897597.m3u8',
    beauty_url: null,
    nutrition_visibility: 'auto',
    show_id: 34,
    video_id: 73153,
    approved_at: 1553195044,
    is_shoppable: true,
    seo_path: '9295813,64486,9299514',
    tips_and_ratings_enabled: true,
    keywords: 'avocado, chia pudding, chicken salad, chickpea chips, deviled eggs, easy, healthy, keto, protein, snacks, vegan, vegetarian',
    servings_noun_plural: 'servings',
    id: 4704,
    aspect_ratio: '1:1',
    name: 'Low-Carb Avocado Chicken Salad',
    language: 'eng',
    brand: null,
    yields: 'Servings: 4',
    promotion: 'partial',
    buzz_id: null,
    created_at: 1546890315,
    thumbnail_alt_text: '',
    num_servings: 4,
    canonical_id: 'recipe:4704',
    cook_time_minutes: 0,
    video_ad_content: 'none',
    description: "This chicken salad is a lunchtime delight! Packed with creamy avocado, tender chicken, and crunchy veggies, it's a healthy and satisfying meal that won't weigh you down. Tossed in a tangy yogurt dressing with a hint of spice, it's a flavor explosion that's perfect for a light meal.",
    thumbnail_url: 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/45b4efeb5d2c4d29970344ae165615ab/FixedFBFinal.jpg',
    is_app_only: false,
    original_video_url: 'https://s3.amazonaws.com/video-api-prod/assets/a0e1b07dc71c4ac6b378f24493ae2d85/FixedFBFinal.mp4',
    country: 'US',
    is_subscriber_content: false,
    servings_noun_singular: 'serving',
    slug: 'low-carb-avocado-chicken-salad',
    prep_time_minutes: 0,
    is_one_top: false,
    updated_at: 1683237600,
    brand_id: null,
    inspired_by_url: null
  },
  {
    draft_status: 'published',
    total_time_minutes: null,
    video_url: 'https://vid.tasty.co/output/121934/hls24_1546897597.m3u8',
    beauty_url: null,
    nutrition_visibility: 'auto',
    show_id: 34,
    video_id: 73153,
    approved_at: 1553195044,
    is_shoppable: true,
    seo_path: '9295813,64486,9299514',
    tips_and_ratings_enabled: true,
    keywords: 'avocado, chia pudding, chicken salad, chickpea chips, deviled eggs, easy, healthy, keto, protein, snacks, vegan, vegetarian',
    servings_noun_plural: 'servings',
    id: 4705,
    aspect_ratio: '1:1',
    name: 'Low-Carb Avocado Chicken Salad',
    language: 'eng',
    brand: null,
    yields: 'Servings: 4',
    promotion: 'partial',
    buzz_id: null,
    created_at: 1546890315,
    thumbnail_alt_text: '',
    num_servings: 4,
    canonical_id: 'recipe:4704',
    cook_time_minutes: 0,
    video_ad_content: 'none',
    description: "This chicken salad is a lunchtime delight! Packed with creamy avocado, tender chicken, and crunchy veggies, it's a healthy and satisfying meal that won't weigh you down. Tossed in a tangy yogurt dressing with a hint of spice, it's a flavor explosion that's perfect for a light meal.",
    thumbnail_url: 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/45b4efeb5d2c4d29970344ae165615ab/FixedFBFinal.jpg',
    is_app_only: false,
    original_video_url: 'https://s3.amazonaws.com/video-api-prod/assets/a0e1b07dc71c4ac6b378f24493ae2d85/FixedFBFinal.mp4',
    country: 'US',
    is_subscriber_content: false,
    servings_noun_singular: 'serving',
    slug: 'low-carb-avocado-chicken-salad',
    prep_time_minutes: 0,
    is_one_top: false,
    updated_at: 1683237600,
    brand_id: null,
    inspired_by_url: null
  },
  {
    draft_status: 'published',
    total_time_minutes: null,
    video_url: 'https://vid.tasty.co/output/121934/hls24_1546897597.m3u8',
    beauty_url: null,
    nutrition_visibility: 'auto',
    show_id: 34,
    video_id: 73153,
    approved_at: 1553195044,
    is_shoppable: true,
    seo_path: '9295813,64486,9299514',
    tips_and_ratings_enabled: true,
    keywords: 'avocado, chia pudding, chicken salad, chickpea chips, deviled eggs, easy, healthy, keto, protein, snacks, vegan, vegetarian',
    servings_noun_plural: 'servings',
    id: 4706,
    aspect_ratio: '1:1',
    name: 'Low-Carb Avocado Chicken Salad',
    language: 'eng',
    brand: null,
    yields: 'Servings: 4',
    promotion: 'partial',
    buzz_id: null,
    created_at: 1546890315,
    thumbnail_alt_text: '',
    num_servings: 4,
    canonical_id: 'recipe:4704',
    cook_time_minutes: 0,
    video_ad_content: 'none',
    description: "This chicken salad is a lunchtime delight! Packed with creamy avocado, tender chicken, and crunchy veggies, it's a healthy and satisfying meal that won't weigh you down. Tossed in a tangy yogurt dressing with a hint of spice, it's a flavor explosion that's perfect for a light meal.",
    thumbnail_url: 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/45b4efeb5d2c4d29970344ae165615ab/FixedFBFinal.jpg',
    is_app_only: false,
    original_video_url: 'https://s3.amazonaws.com/video-api-prod/assets/a0e1b07dc71c4ac6b378f24493ae2d85/FixedFBFinal.mp4',
    country: 'US',
    is_subscriber_content: false,
    servings_noun_singular: 'serving',
    slug: 'low-carb-avocado-chicken-salad',
    prep_time_minutes: 0,
    is_one_top: false,
    updated_at: 1683237600,
    brand_id: null,
    inspired_by_url: null
  },
  {
    draft_status: 'published',
    total_time_minutes: null,
    video_url: 'https://vid.tasty.co/output/121934/hls24_1546897597.m3u8',
    beauty_url: null,
    nutrition_visibility: 'auto',
    show_id: 34,
    video_id: 73153,
    approved_at: 1553195044,
    is_shoppable: true,
    seo_path: '9295813,64486,9299514',
    tips_and_ratings_enabled: true,
    keywords: 'avocado, chia pudding, chicken salad, chickpea chips, deviled eggs, easy, healthy, keto, protein, snacks, vegan, vegetarian',
    servings_noun_plural: 'servings',
    id: 4707,
    aspect_ratio: '1:1',
    name: 'Low-Carb Avocado Chicken Salad',
    language: 'eng',
    brand: null,
    yields: 'Servings: 4',
    promotion: 'partial',
    buzz_id: null,
    created_at: 1546890315,
    thumbnail_alt_text: '',
    num_servings: 4,
    canonical_id: 'recipe:4704',
    cook_time_minutes: 0,
    video_ad_content: 'none',
    description: "This chicken salad is a lunchtime delight! Packed with creamy avocado, tender chicken, and crunchy veggies, it's a healthy and satisfying meal that won't weigh you down. Tossed in a tangy yogurt dressing with a hint of spice, it's a flavor explosion that's perfect for a light meal.",
    thumbnail_url: 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/45b4efeb5d2c4d29970344ae165615ab/FixedFBFinal.jpg',
    is_app_only: false,
    original_video_url: 'https://s3.amazonaws.com/video-api-prod/assets/a0e1b07dc71c4ac6b378f24493ae2d85/FixedFBFinal.mp4',
    country: 'US',
    is_subscriber_content: false,
    servings_noun_singular: 'serving',
    slug: 'low-carb-avocado-chicken-salad',
    prep_time_minutes: 0,
    is_one_top: false,
    updated_at: 1683237600,
    brand_id: null,
    inspired_by_url: null
  },
  {
    draft_status: 'published',
    total_time_minutes: null,
    video_url: 'https://vid.tasty.co/output/121934/hls24_1546897597.m3u8',
    beauty_url: null,
    nutrition_visibility: 'auto',
    show_id: 34,
    video_id: 73153,
    approved_at: 1553195044,
    is_shoppable: true,
    seo_path: '9295813,64486,9299514',
    tips_and_ratings_enabled: true,
    keywords: 'avocado, chia pudding, chicken salad, chickpea chips, deviled eggs, easy, healthy, keto, protein, snacks, vegan, vegetarian',
    servings_noun_plural: 'servings',
    id: 47048,
    aspect_ratio: '1:1',
    name: 'Low-Carb Avocado Chicken Salad',
    language: 'eng',
    brand: null,
    yields: 'Servings: 4',
    promotion: 'partial',
    buzz_id: null,
    created_at: 1546890315,
    thumbnail_alt_text: '',
    num_servings: 4,
    canonical_id: 'recipe:4704',
    cook_time_minutes: 0,
    video_ad_content: 'none',
    description: "This chicken salad is a lunchtime delight! Packed with creamy avocado, tender chicken, and crunchy veggies, it's a healthy and satisfying meal that won't weigh you down. Tossed in a tangy yogurt dressing with a hint of spice, it's a flavor explosion that's perfect for a light meal.",
    thumbnail_url: 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/45b4efeb5d2c4d29970344ae165615ab/FixedFBFinal.jpg',
    is_app_only: false,
    original_video_url: 'https://s3.amazonaws.com/video-api-prod/assets/a0e1b07dc71c4ac6b378f24493ae2d85/FixedFBFinal.mp4',
    country: 'US',
    is_subscriber_content: false,
    servings_noun_singular: 'serving',
    slug: 'low-carb-avocado-chicken-salad',
    prep_time_minutes: 0,
    is_one_top: false,
    updated_at: 1683237600,
    brand_id: null,
    inspired_by_url: null
  },
  {
    draft_status: 'published',
    total_time_minutes: null,
    video_url: 'https://vid.tasty.co/output/121934/hls24_1546897597.m3u8',
    beauty_url: null,
    nutrition_visibility: 'auto',
    show_id: 34,
    video_id: 73153,
    approved_at: 1553195044,
    is_shoppable: true,
    seo_path: '9295813,64486,9299514',
    tips_and_ratings_enabled: true,
    keywords: 'avocado, chia pudding, chicken salad, chickpea chips, deviled eggs, easy, healthy, keto, protein, snacks, vegan, vegetarian',
    servings_noun_plural: 'servings',
    id: 4709,
    aspect_ratio: '1:1',
    name: 'Low-Carb Avocado Chicken Salad',
    language: 'eng',
    brand: null,
    yields: 'Servings: 4',
    promotion: 'partial',
    buzz_id: null,
    created_at: 1546890315,
    thumbnail_alt_text: '',
    num_servings: 4,
    canonical_id: 'recipe:4704',
    cook_time_minutes: 0,
    video_ad_content: 'none',
    description: "This chicken salad is a lunchtime delight! Packed with creamy avocado, tender chicken, and crunchy veggies, it's a healthy and satisfying meal that won't weigh you down. Tossed in a tangy yogurt dressing with a hint of spice, it's a flavor explosion that's perfect for a light meal.",
    thumbnail_url: 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/45b4efeb5d2c4d29970344ae165615ab/FixedFBFinal.jpg',
    is_app_only: false,
    original_video_url: 'https://s3.amazonaws.com/video-api-prod/assets/a0e1b07dc71c4ac6b378f24493ae2d85/FixedFBFinal.mp4',
    country: 'US',
    is_subscriber_content: false,
    servings_noun_singular: 'serving',
    slug: 'low-carb-avocado-chicken-salad',
    prep_time_minutes: 0,
    is_one_top: false,
    updated_at: 1683237600,
    brand_id: null,
    inspired_by_url: null
  }
];
